# Generated by Django 2.2.5 on 2020-10-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='likes',
        ),
    ]
